### PR TITLE
Update Docs

### PR DESCRIPTION
**Pull request by nreinicke**
Some documentation cleanup work:
 - Removes old api documentation source files and adds the `autoapi.extension` to automatically create the API reference from the source code one each documentation build.
 - Removes old documentation build files

There is definitely still work to do on cleaning up our docstrings (and adding docstrings to functions and classes that need them)

### CODE REVIEW

**Comment by jhoshiko** [comment]
@nreinicke Where is the readthedocs check? I don't see it under the checks tab but maybe I missed it.

**Comment by nreinicke** [comment]
Oh interesting it looks like it's only appearing on the checks that are under the review box:

image

but not in the actual checks tab... I don't know why that is...

**Comment by jhoshiko** [comment]
Ah gotcha, looks like that worked! The docs are also looking really good, I like the updates to the input/output sections structurally and the new sections for new features and input file specs are a really good addition. Adding the example section will also go a long way for new users too. Like you mentioned, we can continuously improve the docs but this is a really solid foundation. Thanks again!

**Review by jhoshiko — APPROVED** [review]

**Comment by nreinicke** [comment]
@jhoshiko - Thanks for reviewing all of these!!

**Pull request merged**
