### PR TITLE
expose output_suffix in cosim API

### PR DESCRIPTION
**Pull request by robfitzgerald**
this quick PR exposes output_suffix via the cosim API so that the suffix can be set before creating the scenario.

in both cases where it has been added to a function signature, it has been done with a default value that is consistent with any existing invocations.

### CODE REVIEW

**Comment by robfitzgerald** [comment]
@nreinicke hmm. i did `pip install black --upgrade` just in case, but, running the same black command locally doesn't give me errors. the github action is using the same environment for running black, right? no fancy other .black file or whatever?

```
(hive) rfitzger-36698s:hive rfitzger$ black nrel tests --check
All done! ✨ 🍰 ✨
241 files would be left unchanged.
```

**Comment by nreinicke** [comment]
very weird.. can you confirm your black version? when I pull this branch and apply black (my own version is 23.1.0), I get:

```console
black nrel tests --check
would reformat /Users/nreinick/dev/repos/hive/nrel/hive/state/simulation_state/update/step_simulation_ops.py
would reformat /Users/nreinick/dev/repos/hive/nrel/hive/dispatcher/instruction/instructions.py

Oh no! 💥 💔 💥
2 files would be reformatted, 239 files would be left unchanged.
```

**Comment by nreinicke** [comment]
I suppose we could just pin the black dependency to a specific version [here](https://github.com/NREL/hive/blob/0c965be0bb5aeb5ee7f421ca075e01444bc275b3/pyproject.toml#L48), like, `black==23.1.0` to ensure we're all using the same version.

**Comment by robfitzgerald** [comment]
life is weird. i've installed 23.1.0 but then the version on the cmd line is 22.3.0. i'll uninstall and reinstall.

```
(hive) rfitzger-36698s:hive rfitzger$ pip install black --upgrade
Looking in indexes: https://pypi.org/simple, https://github.nrel.gov/pages/MBAP/mbap-pypi/
Requirement already satisfied: black in /Users/rfitzger/anaconda3/envs/hive/lib/python3.10/site-packages (23.1.0)
Requirement already satisfied: pathspec>=0.9.0 in /Users/rfitzger/anaconda3/envs/hive/lib/python3.10/site-packages (from black) (0.11.0)
Requirement already satisfied: platformdirs>=2 in /Users/rfitzger/anaconda3/envs/hive/lib/python3.10/site-packages (from black) (3.0.0)
Requirement already satisfied: packaging>=22.0 in /Users/rfitzger/anaconda3/envs/hive/lib/python3.10/site-packages (from black) (23.0)
Requirement already satisfied: click>=8.0.0 in /Users/rfitzger/anaconda3/envs/hive/lib/python3.10/site-packages (from black) (8.1.3)
Requirement already satisfied: tomli>=1.1.0 in /Users/rfitzger/anaconda3/envs/hive/lib/python3.10/site-packages (from black) (2.0.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/rfitzger/anaconda3/envs/hive/lib/python3.10/site-packages (from black) (0.4.3)
(hive) rfitzger-36698s:hive rfitzger$ pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://github.nrel.gov/pages/MBAP/mbap-pypi/
Requirement already satisfied: pip in /Users/rfitzger/anaconda3/envs/hive/lib/python3.10/site-packages (23.0.1)
(hive) rfitzger-36698s:hive rfitzger$ which black
/Users/rfitzger/anaconda3/envs/hive/bin/black
(hive) rfitzger-36698s:hive rfitzger$ black --version
black, 22.3.0 (compiled: yes)
```

**Comment by robfitzgerald** [comment]
k. fixed the black version. that did indeed fix it, though the offending lines were reformatted to this:

```python
(
    update_error,
    updated_sim,
) = entity_state_ops.transition_previous_to_next(
    sim, env, instruction_result.prev_state, instruction_result.next_state
)
```

which i found wonk and refactored to this:

```python
result = entity_state_ops.transition_previous_to_next(
    sim, env, instruction_result.prev_state, instruction_result.next_state
)
update_error, updated_sim = result
```

**Review by nreinicke — APPROVED** [review]
looks good to me!

**Pull request merged**
