### PR TITLE
Jdh/update docs

### LINKED ISSUE #111: Vehicle input description describes Station
the [Vehicle](https://nrelhive.readthedocs.io/en/latest/inputs.html#vehicles) section of the inputs documentation mistakenly lists the schema of a stations.csv file.

### PR DESCRIPTION
**Pull request by jhoshiko**
This PR contains the following:

- updates docs with expected file types
- removes all config/doc references to geofences. 
- removes all config/doc references to demand forecast files
- removes demand forecast files from scenarios
- updated vehicle section in the inputs docs to correctly display the vehicles.csv schema

Looks like this also closes #111 

If there are any additional changes to the docs that we think would be beneficial, please let me know!

### CODE REVIEW

**Comment by jhoshiko** [comment]
Hmm, looks like some of our unit tests are still reliant on the Denver demand forecast files. I can update the unit tests or restore the demand forecast files. Let me know what you prefer.

I also noticed references to demand forecast files in both `nrel/hive/dispatcher/forecaster/basic_forecaster.py` and `nrel/hive/config/input.py`. Looks like we could remove references to demand forecast files from `input.py`, and we can leave `basic_forecaster.py` alone since nothing is dependent on it. Let me know what you think!

**Comment by nreinicke** [comment]
I think it would make sense to remove the demand forecast file from the input config at the very least. I would also be open to pulling out the forecaster module but that could be deferred.

**Comment by robfitzgerald** [comment]
right. in general, i think this is the strategy:
- if there are tests testing demand forecasting, we can remove them
- if any tests programmatically load hive with a demand forecast, remove the addition of the forecast
- if any scenario yaml files reference a forecast, remove the reference

for today, we could probably target the least amount of refactoring to get the tests working again, and make it a future task to really clean up all references to forecasting. does that sound right?

forecasting is a useful thingie but it really shouldn't be _hive's problem_. it can instead just a property of a custom InstructionGenerator to load and incorporate any forecasting.

**Review by robfitzgerald — APPROVED** [review]
looks good. thanks for removing those references, they can be distracting when we are introducing people to the model. as for geofence, i have this idea that we could come back to geofences as a special case of fleet id generation (a membership relationship is another way of describing geofencing and probably faster to compute under-the-hood too).

ok pycon's gonna be a party now fo sho!

**Pull request merged**
